//! libmpv link setup.
//!
//! libmpv-sys emits `cargo:rustc-link-lib=mpv` but the library is not in the
//! default linker search path: macOS links against Homebrew's libmpv.dylib,
//! Windows against the MSVC import library generated by
//! scripts/setup-windows.ps1 into vendor/mpv (override with MPV_LIB_DIR).

fn main() {
    println!("cargo:rerun-if-env-changed=MPV_LIB_DIR");
    match std::env::var("CARGO_CFG_TARGET_OS").as_deref() {
        Ok("macos") => macos(),
        Ok("windows") => windows(),
        _ => {}
    }
}

fn macos() {
    for dir in ["/opt/homebrew/lib", "/usr/local/lib"] {
        if std::path::Path::new(dir).join("libmpv.dylib").exists() {
            println!("cargo:rustc-link-search=native={dir}");
            return;
        }
    }
    println!(
        "cargo:warning=libmpv.dylib not found in /opt/homebrew/lib or /usr/local/lib; install mpv via Homebrew"
    );
}

fn windows() {
    let manifest_dir = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let dir = std::env::var("MPV_LIB_DIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| manifest_dir.join("../vendor/mpv"));
    if !dir.join("mpv.lib").exists() {
        println!(
            "cargo:warning=mpv.lib not found in {}; run scripts/setup-windows.ps1 (or set MPV_LIB_DIR)",
            dir.display()
        );
        return;
    }
    println!("cargo:rustc-link-search=native={}", dir.display());

    // Place libmpv-2.dll next to the produced binaries (bins, tests,
    // examples) so `cargo run`/`cargo test` work without touching PATH.
    let dll = dir.join("libmpv-2.dll");
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
    // OUT_DIR = target/<profile>/build/<pkg-hash>/out
    let Some(profile_dir) = out_dir.ancestors().nth(3) else {
        return;
    };
    for dest_dir in [
        profile_dir.to_path_buf(),
        profile_dir.join("deps"),
        profile_dir.join("examples"),
    ] {
        let dest = dest_dir.join("libmpv-2.dll");
        if !dest.exists()
            || dest.metadata().ok().map(|m| m.len()) != dll.metadata().ok().map(|m| m.len())
        {
            if let Err(e) = std::fs::copy(&dll, &dest) {
                println!(
                    "cargo:warning=failed to copy libmpv-2.dll to {}: {e}",
                    dest.display()
                );
            }
        }
    }
}
